# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/google/fugu/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/google/fugu/proprietary/etc/firmware/IT8566_CEC.BIN:system/etc/firmware/IT8566_CEC.BIN \
    vendor/google/fugu/proprietary/etc/firmware/msvdx.bin.0008.0000.0000:system/etc/firmware/msvdx.bin.0008.0000.0000 \
    vendor/google/fugu/proprietary/etc/firmware/msvdx.bin.0008.0000.0001:system/etc/firmware/msvdx.bin.0008.0000.0001 \
    vendor/google/fugu/proprietary/etc/firmware/msvdx.bin.0008.0000.0002:system/etc/firmware/msvdx.bin.0008.0000.0002 \
    vendor/google/fugu/proprietary/etc/firmware/msvdx.bin.0008.0002.0001:system/etc/firmware/msvdx.bin.0008.0002.0001 \
    vendor/google/fugu/proprietary/etc/firmware/msvdx.bin.000c.0001.0001:system/etc/firmware/msvdx.bin.000c.0001.0001 \
    vendor/google/fugu/proprietary/etc/firmware/topaz.bin.0008.0000.0000:system/etc/firmware/topaz.bin.0008.0000.0000 \
    vendor/google/fugu/proprietary/etc/firmware/topaz.bin.0008.0000.0001:system/etc/firmware/topaz.bin.0008.0000.0001 \
    vendor/google/fugu/proprietary/etc/firmware/topaz.bin.0008.0000.0002:system/etc/firmware/topaz.bin.0008.0000.0002 \
    vendor/google/fugu/proprietary/etc/firmware/topaz.bin.0008.0002.0001:system/etc/firmware/topaz.bin.0008.0002.0001 \
    vendor/google/fugu/proprietary/etc/firmware/topaz.bin.000c.0001.0001:system/etc/firmware/topaz.bin.000c.0001.0001 \
    vendor/google/fugu/proprietary/etc/firmware/vsp.bin.0008.0000.0000:system/etc/firmware/vsp.bin.0008.0000.0000 \
    vendor/google/fugu/proprietary/etc/firmware/vsp.bin.0008.0000.0001:system/etc/firmware/vsp.bin.0008.0000.0001 \
    vendor/google/fugu/proprietary/etc/firmware/vsp.bin.0008.0000.0002:system/etc/firmware/vsp.bin.0008.0000.0002 \
    vendor/google/fugu/proprietary/etc/firmware/vsp.bin.0008.0002.0001:system/etc/firmware/vsp.bin.0008.0002.0001 \
    vendor/google/fugu/proprietary/etc/firmware/vsp.bin.000c.0001.0001:system/etc/firmware/vsp.bin.000c.0001.0001 \
    vendor/google/fugu/proprietary/vendor/bin/hwperfbin2jsont:$(TARGET_COPY_OUT_VENDOR)/bin/hwperfbin2jsont \
    vendor/google/fugu/proprietary/vendor/bin/pvrdebug:$(TARGET_COPY_OUT_VENDOR)/bin/pvrdebug \
    vendor/google/fugu/proprietary/vendor/bin/pvrhtb2txt:$(TARGET_COPY_OUT_VENDOR)/bin/pvrhtb2txt \
    vendor/google/fugu/proprietary/vendor/bin/pvrtld:$(TARGET_COPY_OUT_VENDOR)/bin/pvrtld \
    vendor/google/fugu/proprietary/vendor/bin/rscompiler:$(TARGET_COPY_OUT_VENDOR)/bin/rscompiler \
    vendor/google/fugu/proprietary/vendor/firmware/BCM4350C0.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4350C0.hcd \
    vendor/google/fugu/proprietary/vendor/firmware/BCM4350C0_SR2.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM4350C0_SR2.hcd \
    vendor/google/fugu/proprietary/vendor/firmware/PR-ModelCert:$(TARGET_COPY_OUT_VENDOR)/firmware/PR-ModelCert \
    vendor/google/fugu/proprietary/vendor/firmware/fw_bcmdhd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.bin \
    vendor/google/fugu/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd_apsta.bin \
    vendor/google/fugu/proprietary/vendor/firmware/nexus_tv_remote.hex:$(TARGET_COPY_OUT_VENDOR)/firmware/nexus_tv_remote.hex \
    vendor/google/fugu/proprietary/vendor/firmware/rgx.fw.signed.1.72.4.12:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.fw.signed.1.72.4.12 \
    vendor/google/fugu/proprietary/vendor/lib/egl/libEGL_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_POWERVR_ROGUE.so \
    vendor/google/fugu/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so \
    vendor/google/fugu/proprietary/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_POWERVR_ROGUE.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/android.hardware.bluetooth@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.bluetooth@1.0-impl.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.graphics.mapper@2.0-impl.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/android.hardware.keymaster@3.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.keymaster@3.0-impl.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/android.hardware.power@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.power@1.0-impl.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/android.hardware.tv.cec@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.tv.cec@1.0-impl.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/android.hardware.tv.input@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.tv.input@1.0-impl.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/audio.primary.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.default.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/audio.r_submix.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.r_submix.default.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/audio.stub.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.stub.default.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/audio.usb.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.usb.default.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/gralloc.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.default.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/gralloc.moorefield.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.moorefield.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/memtrack.moorefield.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.moorefield.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/tv_input.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/tv_input.default.so \
    vendor/google/fugu/proprietary/vendor/lib/hw/vulkan.moorefield.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.moorefield.so \
    vendor/google/fugu/proprietary/vendor/lib/libDecoderVP9Hybrid.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDecoderVP9Hybrid.so \
    vendor/google/fugu/proprietary/vendor/lib/libIMGegl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libIMGegl.so \
    vendor/google/fugu/proprietary/vendor/lib/libPVRRS.sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libPVRRS.sha1.so \
    vendor/google/fugu/proprietary/vendor/lib/libPVRRS.so:$(TARGET_COPY_OUT_VENDOR)/lib/libPVRRS.so \
    vendor/google/fugu/proprietary/vendor/lib/libPVRScopeServices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libPVRScopeServices.so \
    vendor/google/fugu/proprietary/vendor/lib/libbt-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-vendor.so \
    vendor/google/fugu/proprietary/vendor/lib/libglslcompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libglslcompiler.so \
    vendor/google/fugu/proprietary/vendor/lib/libkeystore-engine-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeystore-engine-wifi-hidl.so \
    vendor/google/fugu/proprietary/vendor/lib/libkeystore-wifi-hidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkeystore-wifi-hidl.so \
    vendor/google/fugu/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/google/fugu/proprietary/vendor/lib/libpvrcpt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpvrcpt.so \
    vendor/google/fugu/proprietary/vendor/lib/libseppr_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libseppr_hal.so \
    vendor/google/fugu/proprietary/vendor/lib/libsrv_um.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsrv_um.so \
    vendor/google/fugu/proprietary/vendor/lib/libufwriter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libufwriter.so \
    vendor/google/fugu/proprietary/vendor/lib/libusc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libusc.so \
    vendor/google/fugu/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/google/fugu/proprietary/vendor/lib/mediadrm/libplayreadydrmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libplayreadydrmplugin.so \
    vendor/google/fugu/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/3dlut.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/3dlut.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/blend.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/blend.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/blur.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/blur.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/colormatrix.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/colormatrix.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/convolve3x3.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/convolve3x3.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/convolve5x5.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/convolve5x5.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/histogram.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/histogram.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/lut.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/lut.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/resize.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/resize.o \
    vendor/google/fugu/proprietary/vendor/lib/rs_intrinsics/yuv_to_rgb.o:$(TARGET_COPY_OUT_VENDOR)/lib/rs_intrinsics/yuv_to_rgb.o \
    vendor/google/fugu/proprietary/vendor/lib/soundfx/libaudiopreprocessing.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libaudiopreprocessing.so
